"""empty message

Revision ID: 1370b907b29b
Revises: cdfbfbc26fac
Create Date: 2016-10-09 10:08:16.721231

"""

# revision identifiers, used by Alembic.
revision = '1370b907b29b'
down_revision = 'cdfbfbc26fac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck_operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Unicode(length=100), nullable=True),
    sa.Column('city', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('id')
    )
    op.add_column(u'user', sa.Column('employing_truck_operator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'truck_operator', ['employing_truck_operator_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'employing_truck_operator_id')
    op.drop_table('truck_operator')
    ### end Alembic commands ###
