"""empty message

Revision ID: af0055da0ff8
Revises: None
Create Date: 2016-08-03 12:44:44.062923

"""

# revision identifiers, used by Alembic.
revision = 'af0055da0ff8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('truck_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Unicode(length=100), nullable=True),
    sa.Column('model_name', sa.Unicode(length=100), nullable=True),
    sa.Column('max_weight_in_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('capacity_in_cubic_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('truck_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.Unicode(length=100), nullable=True),
    sa.Column('city', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('truck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('truck_model_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.Unicode(length=50), nullable=True),
    sa.Column('max_weight_in_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('capacity_in_cubic_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['truck_owner.id'], ),
    sa.ForeignKeyConstraint(['truck_model_id'], ['truck_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truck')
    op.drop_table('truck_owner')
    op.drop_table('role_user')
    op.drop_table('user')
    op.drop_table('truck_model')
    op.drop_table('role')
    ### end Alembic commands ###
